### ISSUE TITLE
apiKey from OAS 

### ISSUE THREAD

**Issue by nicklloyd** [apideck-libraries/portman#103]
The conversion from OAS to Postman gives "interesting" results. 

https://github.com/postmanlabs/openapi-to-postman/issues/326

We should let Portman handle this with dedicated flow that removes from spec, before conversion and then injects an expected auth object back into the generated collection...

**Comment by thim81** [comment]
This is solved in the 1.5.0 release, with the functionality to manage SecurityOverwrite options for methods: apiKey, Bearer Token & basic auth
