### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by schelv** [apideck-libraries/portman#114]
Hi!

I'm interested in using portman to create integration tests.
Are there any example how to do this?
I could not find them in the documentation.

Thank you =)

**Comment by thim81** [comment]
@schelv Indeed, we don't have an example yet. We are preparing an Integration example and a blog post on the topic, so it will come in the next weeks.

**Comment by schelv** [comment]
Ok nice!
If you want someone to test if the example is clear, let me know. =)

**Comment by schelv** [comment]
A question that I already have is: is it possible to reuse operations?
That may be useful for when there are multiple integration tests that have the same initial first steps.
For example something similar to yaml anchors; where you can reference something described elsewhere in the document.

**Comment by thim81** [comment]
@schelv We will surely keep you posted, if you feedback or want to bring contributions, feel free to do so.

The goal of the integration tests, is to re-use the API requests from the OpenAPI the configuration but to be able to overwrite params (body, query params, ...) and define the expected results to validate. The requests will be individual integration tests Postman requests, next to the other Postman requests.

If you are really want to have an example (while we prepare a proper example with explanation), have a look at our integration-tests config : https://github.com/apideck-libraries/portman/blob/main/__tests__/fixtures/portman-integration-tests.crm.json, based on the following OpenAPI spec: https://github.com/apideck-libraries/portman/blob/main/__tests__/fixtures/crm.yml

Which is the integration test configuration we use for the Jest unit tests of Portman.
