### ISSUE TITLE
Undesired property injected in the generated response schema of array type

### ISSUE THREAD

**Issue by adnilsson** [apideck-libraries/portman#133]
I noticed that a property `maxItems: 2` was injected to the generated response schema despite not being present in the original definition. I tried to narrow down the issue and arrived at a trimmed version of the Swagger Petshop.

Giving this as input to portman (both files are attached):
```
> portman -l petshop-api-bug.yaml -o ./petshop-api-bug-postman.json
======================================
 Local Path:            petshop-api-bug.yaml
 Output Path:           ./petshop-api-bug-postman.json
 Portman Config:        portman-config.default.json
 Postman Config:        postman-config.default.json
 Environment:           .env
 Inject Tests:          true
 Run Newman:            false
 Newman Iteration Data: false
 Upload to Postman:     false  
======================================
  ✔ Conversion successful
======================================
🚀 Collection written to: ./petshop-api-bug-postman.json 🚀
======================================
```

While successful, it generates  this schema (pretty printed):
```json
// Response Validation
const schema = {
  "type": "array",
  "items": {
    "required": [
      "name"
    ],
    "properties": {
      "id": {
        "type": "integer",
        "example": 10
      },
      "name": {
        "type": "string",
        "example": "doggie"
      },
      "status": {
        "type": "string",
        "description": "pet status in the store",
        "enum": [
          "available"
        ]
      }
    },
    "type": "object"
  },
  "maxItems": 2
}
```

Notice the last property.

## Possible cause and a workaround

If you look at [response test generation code](https://github.com/apideck-libraries/portman/blob/4172004f486b650e2b79aa05bbb2f9953d7b6e78/src/application/tests/testResponseJsonSchema.ts), you can see that `traverse` in  `convertUnsupportedJsonSchemaProperties`  explicitly checks for and deletes `minItems: 2` and `maxItems: 2`. 
A comment reveals another part of the conversion is known to inject these unwanted properties.

The branching condition, specifically`obj[k]?.type === 'array'`, hints that this is is only an issue when the type is set to `array`.
However, if the schema has an array as the outermost type, for instance
```yaml
schema:
  type: array
  items: 
    $ref: '#components/MyItems'
```
as in my example, then we'd never check for f the first loop immediately iterates over the keys `type` and `items`.

### The workaround

If my guess of the cause is correct, just changing the schema to begin with an object instead of an array type should be enough to make `traverse` see the array and delete the `maxItems` field.

Modified response schema in `petshop-api-bug.yaml`:
```yaml
schema:
    type: object
    required:
      - pets
    properties:
      pets:
        type: array
        items:
          $ref: '#/components/schemas/Pet'
```

And this works.  The generated schema is now: 

```json
{
  "type": "object",
  "required": [
    "pets"
  ],
  "properties": {
    "pets": {
      "type": "array",
      "items": {
        "required": [
          "name"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "example": 10
          },
          "name": {
            "type": "string",
            "example": "doggie"
          },
          "status": {
            "type": "string",
            "description": "pet status in the store",
            "enum": [
              "available"
            ]
          }
        },
        "type": "object"
      }
    }
  }
}
```

## Versions
```
> portman --version
1.8.0
```
On Ubuntu 20.04 LTS running under WSL.

## Attachments
[petshop-api-bug.zip](https://github.com/apideck-libraries/portman/files/7077178/petshop-api-bug.zip)

**Comment by thim81** [comment]
@adnilsson Thanks for reporting this. You item contains plenty of details, including the OpenAPI file and Postman outcome, which will help us to reproduce the issue.

The unwanted max items is something that is inject by the openapi-to-postman package, which Portman uses under the hood.

We will look into the issue and see how we can overcome this. Your suggestion is certainly a route we will investigate.

**Comment by thim81** [comment]
@adnilsson We have a fix ready. I'll add some more tests to include it in our test coverage and put it in a PR.

<img width="1495" alt="2021-08-30 at 16 27 41@2x" src="https://user-images.githubusercontent.com/952446/131355130-49a3faee-e727-41fe-a18c-eb1a0f82b73b.png">

The generated JSON schema result would be:

```json
{
   "type":"array",
   "items":{
      "required":[
         "name"
      ],
      "properties":{
         "id":{
            "type":"integer",
            "example":10
         },
         "name":{
            "type":"string",
            "example":"doggie"
         },
         "status":{
            "type":"string",
            "description":"pet status in the store",
            "enum":[
               "available"
            ]
         }
      },
      "type":"object"
   }
}
```

The fix will most likely land in the next release.

**Comment by thim81** [comment]
@adnilsson Today we release Portman 1.8.1, which contains a fix for this item.

I'm going to close the item, if the issue reappears, feel free to open a new issue or reopen this item.

**Comment by jonathanevans-freesat** [comment]
@thim81 I am still experiencing this issue using version 1.8.1 installed via npm.

Using the OpenApi spec from OPs attachment, I still see `"maxItems": 2`

Having inspected the source code of:

`/usr/local/lib/node_modules/@apideck/portman/dist/application/tests/testResponseJsonSchema.js` 

it does not seem to include the fix from #134

I am not well versed in TypeScript, so I may be missing something here.

Please let me know if there is anything I need to do to be able to use the fix mentioned above.

**Comment by thim81** [comment]
@jonathanevans-freesat Would it be able that you share your OpenApi Specification with us?

That way we can run the conversion and debug portman while doing.

**Comment by thim81** [comment]
@jonathanevans-freesat I can confirm that something went wrong with the last release and the maxItems fixes were not included.

We are going to do a patch release tomorrow, with another bug fix, normally the issue will be solved in that release.

**Comment by thim81** [comment]
@jonathanevans-freesat We fixed the build and just released version 1.8.2 which includes the maxItems fixes.

Could you verify if the maxItems issue is resolved for you?

**Comment by jonathanevans-freesat** [comment]
@thim81 I have just tested this using version 1.8.2 and can confirm this is now working as expected.

Thanks for the prompt fix.

**Comment by thim81** [comment]
@jonathanevans-freesat Thanks for reporting it. Something went wrong with the build, so apologies for the inconvenience.
Going to close the issue.

**Comment by chyde80** [comment]
Still seeing this issue in portman 1.22.0 - except my random injection is `"maxItems":1` - my OAS has no `maxItems` specified in the entire spec.
