### ISSUE TITLE
Textual improvement in blog article

### ISSUE THREAD

**Issue by yourithielen** [apideck-libraries/portman#138]
From https://blog.apideck.com/announcing-portman:

> API testing libraries like Portman make it easy to ensure your APIs are reliable while keeping your documentation in sync with the API definition.

Shouldn't this read:
> API testing libraries like Portman make it easy to ensure your APIs are reliable while keeping your documentation in sync with the API **implementation**.

Or. what else is meant by API definition? And what is meant by documentation? The spec?

Keep up the good work with Portman!

**Comment by Gdewilde** [comment]
You're correct! Can you send in a PR?

**Comment by yourithielen** [comment]
> You're correct! Can you send in a PR?

Sure but the text is from the blog, which is not in this repo it seems?

**Comment by Gdewilde** [comment]
Ah sorry. Updated ;)
