### ISSUE TITLE
Collection Authorization Missing in Portman Output File

### ISSUE THREAD

**Issue by inoclafsemaj** [apideck-libraries/portman#142]
When using Newman to test our collection, Newman is unable to successfully use the Output file generated by Portman - (for example, the "crm.postman.json" listed in the examples Cli Options configuration listed as "output"). The result is that all tests in the collection fail (they all have 403 Forbidden). But, when I use a manual export of the collection via Postman using their Export feature, Newman is successful in running the tests. 403 suggested to me an authorization problem so I dug a little further...

I have examined both files (the collection JSON generated by Portman vs the one by Postman), and while they predominantly contain the exact same data, the Portman generated file is missing a critical object in the JSON body: the "auth" object. The Postman export of the collection includes this object at the very end of the file before the "info" object that ends the document JSON. 

"auth": {
		"type": "bearer",
		"bearer": [
			{
				"key": "token",
				"value": "{{autoBearerToken}}",
				"type": "string"
			}
		]
	},

This "auth" object contains the parent collection authorization (selected in Postman). In this case, I'm using a variable stored in the environment variables. I realize this may not be a bug, but perhaps an improvement suggestion? Very possible I'm overlooking a Portman feature here.

Should there be a way for the Portman generated output file of the collection to include the authorization for the entire collection? I might find a way to work around this by using the .env file (via the ### PORTMAN INJECTED VARIABLES) to create and store a collection variable for the bearer token (instead of the environment variable we are using right now), though that would need to be updated every hour as the token expires.

Thank you!

**Comment by thim81** [comment]
@inoclafsemaj 

In the global section of the config you can define "securityOverwrites", which provides support for the bearer method. 

Have a look at the readme, that explains the details.

**Comment by thim81** [comment]
Via the "securityOverwrites" you can set the token as a variable. 

Through the globale > collectionPrerequest you could fetch the token and assign it as the variable. 

An example for Auth0: https://gist.github.com/thim81/a1e218272fbcf934bcbc2d19cab70fef

**Comment by thim81** [comment]
@inoclafsemaj If this answers & examples were helpful, feel free to close this issue.

**Comment by inoclafsemaj** [comment]
Yes, thank you @thim81

**Comment by inoclafsemaj** [comment]
> @inoclafsemaj
> 
> In the "globals" section of the config you can define "securityOverwrites", which provides support for the bearer method.
> 
> Have a look at the [globals section ](https://github.com/apideck-libraries/portman#portman---globals-property) in the readme, that explains the details.
> 
> ```
> "securityOverwrites": {
>       "bearer": {
>         "token": "{{bearerToken}}"
>       }
>     }
> ```

@thim81 - I tried this but it is not working like I expected. The postman collection JSON file appears to still be missing that critical auth key and value pair. For reference, when I paste this into the Portman generated Postman collection, it works
"auth": {
		"type": "bearer",
		"bearer": [
			{
				"key": "token",
				"value": "{{autoBearerToken}}",
				"type": "string"
			}
		]
	},

I think Newman may be looking for that "auth" key and it is absent from the Portman generated collection.

Your code for auto requesting the bearer token from the pre-request script was a big help, Thank you!
But, I added the security overwrite in Globals as you instructed, however, that is not working.

**Comment by thim81** [comment]
@inoclafsemaj 

Could you share your OpenAPI file, so that we could review the way you have setup your security?

There are multiple way how you can set the bearer token.

An example where none of the default "auth" stuff is used, but just a simple HTTP header is defined:

OpenAPI Request:

```
  '/portal/v1/messages':
    get:
      operationId: get-messages
      summary: Get all send messages
      parameters:
        - $ref: '#/components/parameters/X-OAuth2'
        - $ref: '#/components/parameters/application-json'
      responses:
        '200':
          description: Success
             
```

Where the bearer token is set as a header in the `X-OAuth2` schema like so:

```
components:
  parameters:
    X-OAuth2:
      in: header
      name: Authorization
      required: false
      schema:
        type: string
        example: 'Bearer {{oauth_access_token}}'
        default: 'Bearer {{oauth_access_token}}'
      description: Oauth2 token to authorize requests.
```

By using the `default: 'Bearer {{oauth_access_token}}'` like so in OpenAPI,  which includes Postman variables, you can just use it directly.

<img width="1491" alt="2021-09-20 at 21 45 22@2x" src="https://user-images.githubusercontent.com/952446/134065264-2f4533e5-ef6f-4aab-a39b-8068739a5166.png">

**Comment by inoclafsemaj** [comment]
@thim81 - I will ask if it is okay to share it. We are in an early phase of development. What you have outlined for X-OAuth2 has not been setup in our schema. I'm sure it is a possibility for us.  Right now, on the collection in Postman, I'm selecting Bearer for authorization and including the variable there, which is recorded in our Environment Variables (in Postman). All subsequent requests use "Inherit from Parent" for the authorization (set via Postman).

![Screen Shot 2021-09-20 at 2 26 43 PM](https://user-images.githubusercontent.com/13210182/134078120-58afde44-57f1-42a5-883e-1b0b5600b0bc.png)

Not sure if it is worth it for Postman to place the "auth" key/value pair that Postman does on an export of the collection. At least for US and *right now*, it would be incredibly convenient. I can always manually export the file from Postman, then use that collection JSON with Newman, or manually paste in the "auth" key/value into the Portman-generated collection to get it working. Not sure if others would find this useful or if we are the oddballs here. :)

**Comment by thim81** [comment]
@inoclafsemaj Is there anything related to auth documented in the OpenApi file? Because that is what Portman does, it uses the OpenApi spec and allows you to modify/extend/overwrite the specification while converting it to postman. 

If it has nothing on the authentication, so will your users not be able to figure out how to authenticate since it is not documented. 

Without OpenApi file it is harder to figure out what it is the best way to move forward. 

For now you have the following options in OpenApi:
- define a header for the bearer
- use the "Auth" from OpenApi

Injecting an auth snippet, is not so straightforward.

**Comment by inoclafsemaj** [comment]
Ok. Thank you for your help! We'll keep this in mind as we go forward.

**Comment by inoclafsemaj** [comment]
We had to move on to other work, but are confident we'll be able to get it running as anticipated when we revisit this. Thank you.
