### ISSUE TITLE
Syncing to Postman

### ISSUE THREAD

**Issue by nicklloyd** [apideck-libraries/portman#164]
Getting some funky behaviour when syncing to Postman. Often have uploads fail 2 or 3 times (slow) before completing a successful upload.

Going to rework some of our approach 

![image](https://user-images.githubusercontent.com/1973952/140494644-588dc45d-6bd9-42cb-9e9e-633d877bb8c0.png)

**Comment by thim81** [comment]
This will be part of the 1.10 release.
