### ISSUE TITLE
Security tests: No auth

### ISSUE THREAD

**Issue by savage-alex** [apideck-libraries/portman#221]
**User Story**
As an API tester
I want to have a test that calls each API operation with no security
So that any miss configured APIs without security are found automatically

**Acceptance Criteria**
* New configuration exists to enable feature
* New folder for path + (No Authentication) exists when imported to Postman
* Calls are made with authorization set to No Auth
* Response codes and schema validation match the 401 or 403 schemas

**Comment by nicklloyd** [comment]
Hey Alex - have you looked into variation testing?

**Comment by nicklloyd** [comment]
ie: https://github.com/apideck-libraries/portman/blob/main/examples/testsuite-variation-tests/portman-config.crm.json#L33-L57

**Comment by savage-alex** [comment]
I had read the docs but failed to notice the examples here! I will setup some scenarios thanks!
