### ISSUE TITLE
Integers with format of int32 & 64 given an error 

### ISSUE THREAD

**Issue by savage-alex** [apideck-libraries/portman#225]
Given the following openAPI (attached resolved json and native un-resolved yaml  - had to rename them to .txt to allow for upload)

When the schema validation is enabled, the following response is seen in postman:
![image](https://user-images.githubusercontent.com/25430683/146986110-77d3f614-a2b4-46d0-af18-3865bf1905a7.png)
[AdvancedComputerSoft-demo-advanced-car-inventory-1.1.2-swagger.yaml.txt](https://github.com/apideck-libraries/portman/files/7757549/AdvancedComputerSoft-demo-advanced-car-inventory-1.1.2-swagger.yaml.txt)
[AdvancedComputerSoft-demo-advanced-car-inventory-1.1.2-resolved.json.txt](https://github.com/apideck-libraries/portman/files/7757550/AdvancedComputerSoft-demo-advanced-car-inventory-1.1.2-resolved.json.txt)

API is here: https://app.swaggerhub.com/apis/AdvancedComputerSoft/demo-advanced-car-inventory/1.1.2

**Comment by thim81** [comment]
Hi @savage-alex 
The "pm. response. to. have. jsonSchema" function is using AJV behind the scenes.
Portman passed 2 things to this function: the JSON schema (`schema`) & AJV options (`{unknownFormats: ["int32", "int64"]}`

If we don't include the options, Postman will throw an error like: `unknown format "int32"`

So Portman generates a Schema Validation and passing along the schema as an inline variable and the AJV options.

Does this throw an error?

**Comment by savage-alex** [comment]
No error just something I noticed in the schema validation that looked suspect

**Comment by thim81** [comment]
Nothing to worry about, it is a necessary part of the AJV configuration for the Schema validation, which is embedded in Postman.
