### ISSUE TITLE
Contract test: Handle responses with no body

### ISSUE THREAD

**Issue by thim81** [apideck-libraries/portman#242]
### Discussed in https://github.com/apideck-libraries/portman/discussions/239

<div type='discussions-op-text'>

<sup>Originally posted by **savage-alex** January 14, 2022</sup>
204 is a popular status code for PUT, POST and DELETE operations and MUST not have a response body says the[ RFC7231 ](https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5)

In portman contract tests it correctly omits any body or schema checks if there is no content in the and API definition for the 2xx response. What it currently does not to is add a check for response body to be empty style test such as 
pm.test("response should be empty", function () {
    pm.response.to.not.be.withBody;
});

Is this something that would be useful to add to ensure we are not returning bodies when the contact is saying we shall not?

</div>

**Comment by AliKhalili** [comment]
@savage-alex It works very well, Thank you @thim81
