### ISSUE TITLE
[Config] Throw error when globals objects not specified

### ISSUE THREAD

**Issue by fr4ngus** [apideck-libraries/portman#261]
Hi, first of all, thank you for you work, I started using it and I find the tool interesting especially for CI/CD use.

I think it would be interesting, to throw an error by stopping the execution of the program, when the user has not filled the global object in the config.

Particularly when specifying a baseUrl (as a CLI parameter, or via the cliOption file), it doesn't use it in the resulting Postman collection.

[CollectionWriter.ts](https://github.com/apideck-libraries/portman/blob/main/src/application/CollectionWriter.ts#L25)

**Steps to reproduce the "issue":**

1. remove globals part of the [portman-config.crm.json](https://raw.githubusercontent.com/apideck-libraries/portman/main/examples/cli-options/portman-config.crm.json)
2. portman --cliOptionsFile ./examples/cli-options/portman-cli-options.json

**Result:**

The baseUrl param specified in [portman-cli-options.yaml](https://raw.githubusercontent.com/apideck-libraries/portman/main/examples/cli-options/portman-cli-options.yaml) is not write in the resulting generated collection.

**Comment by nicklloyd** [comment]
Hi @fr4ngus - the baseUrl in the global config acts as an override of the url in the open api spec itself.

So not providing one is still a valid configuration…

**Comment by fr4ngus** [comment]
I will re-specify my statement for more clarity.

I wasn't talking about the property baseUrl in the config file, I am talking about the fact that when we omit the global part from the portman-cli-option config, but specify a baseUrl in the portman-config, it will not be used in the generated postman collection (caused in the code it will skip the part that override the URL in Open API Spec).

**Comment by nicklloyd** [comment]
Ah I sorry I miss understood.

Think there might be more cases like this - that having a bit of a validation layer over all would help developers.

That said I wonder if we're not looking at a bug where the baseUrl is not being passed in properly.
