### ISSUE TITLE
Problem with variable on TestContent with responseBodyTests

### ISSUE THREAD

**Issue by jdevosMagento** [apideck-libraries/portman#288]
Hello, It's me again :-D 

I have a problem with the test content services on the responseBodyTests.

I use for all my test a prerequest-scripts for setting differents variables, exemple : 

```
{
    "openApiOperation": "XX::/xxxxxx",
    "responseBodyTests": [
        {
            "key": "Xxxxxx[0].Xxxxxx[0].Xxxxxx",
            "value": "{{variable_prerequest}}"
        }
    ]
}
```
With postman CLI, Newman return this with an error in red color

1. [XX]::/xxxxxx - Content check if value for 'Xxxxxx[0].Xxxxxx[0].Xxxxxx' matches '{{sku}}'

Sku doesn't seem valued, Does it exist and is it a bug or is it not planned? 

Thank you!

**Comment by thim81** [comment]
@jdevosMagento 
I haven't found the time yet to test it myself but could provide me some details, that would help during the investigation:
- How does the content check looks like in Postman?
- Does the test also fails in Postman or only in Newman?
- What version of Newman are you using?

**Comment by thim81** [comment]
@jdevosMagento 

There is a mis alignment, in your pre-request script you are setting an environment variable `pm.environment.set`
while Portman is looking for collection variable `pm.collectionVariables.get`.

**Comment by jdevosMagento** [comment]
Oh yes...

So i have to put on environment for variables on overwriteRequestPathVariables/Body and on collectionsVariables for testing

**Comment by thim81** [comment]
There is a difference in implementation, the overwrite uses the {{}} so no matter if it an environment/collection/.... variable.

For the content check, it is not possible to use the raw variable. The assertion can only be done on "value", not a variable; this is why we use `pm.collectionVariables.get` which converts the variable into a value before we are doing the "eql" test.

Some references:
https://community.postman.com/t/how-can-postman-compare-the-value-of-a-written-variable-with-the-value-from-json/14284/2
https://community.postman.com/t/how-to-validate-an-environment-variable-in-a-response-of-get-request/7142/9

**Comment by jdevosMagento** [comment]
Ok thanks for the links, I'll see to use collectionVariables for this

**Comment by thim81** [comment]
In you situation, I would or:
- modify your pre-request script to use: pm.collectionVariables.set('variable_prerequest', variablePrerequest)

**Comment by thim81** [comment]
@jdevosMagento Where you able to overcome the issue?

**Comment by jdevosMagento** [comment]
Yes it's good, I was able to solve my problem using collectionVariables, thank you for your help
