### ISSUE TITLE
OpenApi-format filtering

### ISSUE THREAD

**Issue by nicklloyd** [apideck-libraries/portman#29]
When passing the following as filter options: 

```
{
  "operationIds": ["proxyCall"],
  "tags": ["Proxy"]
}
```

The operations is removed, but the tag is not resulting in an empty folder in the Postman collection.

portman: 0.1.0
openapi-format being using within portman: 1.2.3

**Comment by thim81** [comment]
@nicklloyd what is the actual result? And what is expected?

**Comment by thim81** [comment]
Fixed in the 1.2.5 release of [openapi-format](https://www.npmjs.com/package/openapi-format)
