### ISSUE TITLE
Allow reading tests from files

### ISSUE THREAD

**Issue by wedi** [apideck-libraries/portman#304]
It's possible to read prerequest scripts from a file by prefixing it with `file:`. It would be great if that were possible for tests, too.

This configuration
```json
  "tests": {
    "extendTests": [
      {
        "openApiOperation": "*::/*",
        "tests": [
          "file:portman/tests.js"
        ]
      }
    ]
  },
```
sets all tests to the literal value `file:portman/tests.js`.

**Comment by jopucpla** [comment]
+1

Actually could manage to include the feature by adding this to extendTest.ts (same as done in preRequest)


  const scriptContents = extSetting.tests.map(tst => {
    if (tst.startsWith('file:')) {
      return getScriptContent(tst.replace('file:', ''))
    } else {
      return tst
    }
  })

Same behavior achieved

[extendTest.txt](https://github.com/apideck-libraries/portman/files/8387406/extendTest.txt)

**Comment by thim81** [comment]
@vinh0604 Would you mind contributing again and adding support for the `file:` logic for the `extendTests` function?

**Comment by thim81** [comment]
or @jopucpla That would make sense, so if you are up for it, would you be interested in creating a PR for it?

**Comment by thim81** [comment]
@wedi @jopucpla A PR has been provided, so support for using `file:` for `extendTest` will land in the next release of Portman.

**Comment by thim81** [comment]
Portman 1.15.1 has just been released with the enhancement for "file:" inclusions for `extendTest`

**Comment by wedi** [comment]
Wow. That's a quick response. Thank you. ❤️

**Comment by jopucpla** [comment]
Thank you ! :)
