### ISSUE TITLE
Can't target HEAD with wildcard

### ISSUE THREAD

**Issue by gpa** [apideck-libraries/portman#306]
Hi there,
The following configuration fails to modify the header, if the path is changed to GET or POST, it then works.
```
{
  "version": 1.0,
  "overwrites": [
    {
      "openApiOperation": "*::/*",
      "overwriteRequestHeaders": [
        {
          "key": "request-id",
          "disable": true
        }
      ]
    }
  ]
}
```
```
openapi: 3.0.1
info:
  title: Test
  version: 1.10.0
paths:
  /test:
    head:
      summary: Get test
      operationId: get-test
      responses:
        '200':
          description: Wallets list
    parameters:
      - &ref_1
        name: request-id
        in: header
        required: false
        schema:
          type: string
        example: 'abc'
```
Changing wildcard to `"*::/test"` does not help either.

**Comment by thim81** [comment]
@gpa 
We just extended the supported OpenAPI methods.

In the next release, Portman will support: 'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD', 'TRACE'

**Comment by thim81** [comment]
Portman release 1.15.1 contains support for: 'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD', 'TRACE'
