### ISSUE TITLE
Numbers with format of double error in schema validation

### ISSUE THREAD

**Issue by savage-alex** [apideck-libraries/portman#307]
I have the following openAPI: https://app.swaggerhub.com/apis/AdvancedComputerSoft/demo-advanced-car-inventory/1.1.4#/Car with a property of price against the car schema

When converted through portman into a postman collection we see the error that double isnt a known format

this is resolved via adding it to the unknownFormats array as is done for int32 and int64 
![image](https://user-images.githubusercontent.com/25430683/161066245-f2abaa2c-d0c0-466a-b367-6414d1d27e5b.png)

https://github.com/apideck-libraries/portman/blob/133314ebb64b1559f0ac432688e211e066bf266b/src/application/tests/testResponseJsonSchema.ts  added support for float
Please can double be added to the list?

**Comment by savage-alex** [comment]
It looks like I am running an old version and float was added here https://github.com/apideck-libraries/portman/blob/133314ebb64b1559f0ac432688e211e066bf266b/src/application/tests/testResponseJsonSchema.ts we still need double adding?

**Comment by nicklloyd** [comment]
Indeed `float` was added recently by @danielkocot. Should be easy enough to add `double`, just need to be sure the change is picked up in tests/snapshots and examples...

**Comment by savage-alex** [comment]
Thanks for comment Nick. I was going to add it but unsure how to do the tests. @AliKhalili is this something you could do for us please?

**Comment by thim81** [comment]
The PR from @AliKhalili has landed, so in the next release of Portman schema validation for "double" will be included.

Thanks again @AliKhalili for your contribution. It is highly appreciated.
