### ISSUE TITLE
OpenAPI v3.1 Support

### ISSUE THREAD

**Issue by philsturgeon** [apideck-libraries/portman#314]
Thanks for making this excellent package. I wanted to make a quick issue to track the progress towards supporting OpenAPI v3.1, because it's been out for over a year now and it's excellent. It adds a lot of convenient functionality and lines up perfectly with JSON Schema, which could actually simplify your toolchain rather well as you can just use any of the vast amounts of JSON Schema tooling instead of the subset of tooling which understands what an OpenAPI Schema object.

Here's a guide to the differences written for end-users, but it should help make things fairly clear to tooling vendors 

https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

If you say you'll be working on it I can update [openapi.tools](https://openapi.tools) to reflect that. 

Let me know if you have any questions or need any help with the upgrade process.

**Comment by schelv** [comment]
This would be very useful.

@thim81 are there any plans for supporting 3.1?

**Comment by thim81** [comment]
@schelv We have it on the roadmap to bring support for OpenAPI 3.1.
Since a part of the OpenAPI conversion is done by Postman package [openapi-to-postman](https://github.com/postmanlabs/openapi-to-postman), we are waiting for their OpenAPI 3.1 implementation is stabilised.

It is also linked to finding the time to implement the OpenAPI 3.1 changes in Portman, due to summer the maintainers have less available time.

**Comment by philsturgeon** [comment]
@thim81 I completely understand the time issue. Thankfully though the load has been made a little lighter, as it looks like openapi-to-postman now supports v3.1! 🙌🏻  https://github.com/postmanlabs/openapi-to-postman/issues/499

**Comment by thim81** [comment]
Indeed @philsturgeon, we saw the update from OpenApi-to-postman supporting OpenApi 3.1

We are making plans to start development to support OpenApi 3.1. So we will be making progress soon.

**Comment by thim81** [comment]
We have upgraded and released Portman to use the latest version of openapi-to-postman (version 4.9.0) which supports OpenAPI 3.1.

This means that Portman supports OpenAPI 3.1.
We will follow-up if there are cases that we do not yet cover in separate Github tasks.
