### ISSUE TITLE
Variation tests not generated for 'application/merge-patch+json' route body

### ISSUE THREAD

**Issue by yelob** [apideck-libraries/portman#332]
When trying to generate variation tests for a PATCH route, specifying 'application/merge-patch+json' in the OAS3 schema seems to block creation of the tests.

Generates tests:
```
"paths": {
    "/": {
      "patch": {
        "description": "Updates existing item",
        "operationId": "patch-item,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/patchItem"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Successfully updated the item."
          },
          "400": {
            "$ref": "#/components/responses/400badrequest"
          }
        }
      }
    }
  }
```

Does not generate tests:
```
"paths": {
    "/": {
      "patch": {
        "description": "Updates existing item",
        "operationId": "patch-item,
        "requestBody": {
          "content": {
            "application/merge-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/patchItem"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Successfully updated the item."
          },
          "400": {
            "$ref": "#/components/responses/400badrequest"
          }
        }
      }
    }
  }
```
Note that the requestBody content is the only thing different.

The strange thing is that Portman knows about this type, because when it does generate tests, it properly sets the Content-Type header to 'application/merge-patch+json' in the generated tests.

Is this a bug, or am I doing something wrong? Thanks.

**Comment by thim81** [comment]
@yelob 

Currently Portman focusses on JSON support for the content-types.
Supporting multiple different content-types is another complexity, but is not the case looking at your request.

Do you happen to know a list of official supported JSON content-types? 

That way we can consider extending the support for JSON variants as content-types.

**Comment by yelob** [comment]
No, I think there's just some basic guidelines for how a content-type should be formatted; no official list. 

I can see how you wouldn't want to have custom logic in here for every random content-type. My suggestion would be to ignore content-type and assume JSON, but if that's not desirable, you could make it a configuration option.

**Comment by thim81** [comment]
Making the assumption for Portman that the content-type is JSON, would be a wrong choice, since we aim to bring support for more types, like the content-type application/x-www-form in the future. 

The goal of Portman is to keep the configuration as simple as possible, but still offer flexibility to steer the conversion. Adding a specific config for variants of content-types, feels like a wrong direction 

We could provide a chain of logic:
1) check if content-type === application/json
2) check if the content-type contains "json" 

Would that solve your use-case?

**Comment by yelob** [comment]
That would definitely solve my use-case.

**Comment by thim81** [comment]
@yelob Could you share your Portman configuration file? So we can reproduce your portman setup.

**Comment by thim81** [comment]
@yelob 

Looking at your example

```
"paths": {
    "/": {
      "patch": {
        "description": "Updates existing item",
        "operationId": "patch-item,
        "requestBody": {
          "content": {
            "application/merge-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/patchItem"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Successfully updated the item."
          },
          "400": {
            "$ref": "#/components/responses/400badrequest"
          }
        }
      }
    }
  }
```

What were you expected tests for?
Since the `204` has no response body nor headers?
We are missing some context on what is expected as tests, hence the question for the portman config.

**Comment by yelob** [comment]
Oh, sorry about that. I've attached the files you can use to reproduce the issue.
[temp-portman-config..txt](https://github.com/apideck-libraries/portman/files/8832693/temp-portman-config.txt)
[temp-schema.txt](https://github.com/apideck-libraries/portman/files/8832694/temp-schema.txt)

**Comment by thim81** [comment]
@yelob There is PR in the making to offer for JSON variants as content-type.

Your provided OAS & configuration, helped to reproduce the issue, so thanks for sharing them.

**Comment by yelob** [comment]
Hi @thim81 - Just checking in to see if you had a timeline in mind for when you will cut a new version. Any info appreciated.

Thanks!

**Comment by thim81** [comment]
hi @yelob ,

We are adding improvements to the anyOf, allOf, oneOf support, which we want to finish as part of the new release.
Difficult to say about a timeline, I'm hoping to land everything next week.

**Comment by thim81** [comment]
@yelob  We just release Portman v1.17, which includes the support for JSON content-types variants.
The release should solve your reported issue.
