### ISSUE TITLE
`POSTMAN_COLLECTION_UID` ignored if collection name is not as expected

### ISSUE THREAD

**Issue by tillig** [apideck-libraries/portman#353]
I wanted to create an empty collection in Postman and have my Portman tests generated into that, but it seemed to ignore my empty collection and want to create a new one. What I discovered is that if the collection _name_ is not what is expected based on the generated tests, the sync will create a new collection even if you've specified a UID.

Repro 1 (Unexpected Behavior):

1. Create a simple specification and some Portman tests. Using the examples, this would generate a collection called `CRM API`.
2. Create a new collection in your Postman workspace. Call the new collection `My CRM Tests`.
3. Get the workspace name and collection UID for the `My CRM Tests` collection. This is where you want the tests to sync.
4. Set up a `.env` file with a `POSTMAN_API_KEY`, `POSTMAN_WORKSPACE_NAME`, AND `POSTMAN_COLLECTION_UID`. Use the workspace name and collection UID for the `My CRM Tests` collection.
5. Generate the tests with Portman and use the `--syncPostman` flag.

When the collection is synchronized, the `My CRM Tests` collection will remain empty and a _new collection_ called `CRM API` with a different UID will be created.

Repro 2 (Collection Name Workaround):

1. Create a simple specification and some Portman tests. Using the examples, this would generate a collection called `CRM API`.
2. Create a new collection in your Postman workspace. Call the new collection `CRM API`. **This is the weird part.** It must match the name in the generated set of tests!
3. Get the workspace name and collection UID for the `CRM API` collection. This is where you want the tests to sync.
4. Set up a `.env` file with a `POSTMAN_API_KEY`, `POSTMAN_WORKSPACE_NAME`, AND `POSTMAN_COLLECTION_UID`. Use the workspace name and collection UID for the `CRM API` collection.
5. Generate the tests with Portman and use the `--syncPostman` flag.

When the collection is synchronized, it will go into the specified collection, but only because the name _and_ UID of the collection matched.

**Comment by thim81** [comment]
@tillig Portman is designed to create a new Postman collection. Once the collection is created, Portman keeps track of the newly generated collection and uses the UID for updating/replacing that collection. 
The list of Postman collections is locally cached for performance reasons, so that could explain the behaviour you described.

Could you retry your flow and pay attention to `tmp/.portman.cache.json` or the cli paramate `--postmanRefreshCache true`

**Comment by tillig** [comment]
Then maybe I misunderstood how that was supposed to work based on the current README:

> To enable automatic uploads of the generated Postman collection through Portman, follow these steps:
>
> 1. Get your Postman API key
> 2. Goto the root folder of your project
> 3. Copy [env-postman-app-example](https://github.com/apideck-libraries/portman/blob/main/.env-postman-app.example) as .env in the root folder of your project
> 4. Enter your Postman API key in a local `.env` file, as `POSTMAN_API_KEY=[replace with Postman api key]`
>
> **Next to the Postman API key, you can also pass along the Postman Workspace name & the specific Postman Collection UID.**

That last line (bold/emphasis mine) is what is misleading. You actually _can't_ specify the UID, at least, not if the name of the collection doesn't match. However, if the _name matches_ **and** the _UID matches_ then it works.

It seemed like the "always create a new collection" feature was the `--postmanFastSync`, which isn't what I'm using.

Is this a case where the documentation is wrong and needs to be updated?

I haven't tried it yet, but what happens if I let Portman create the collection and then _I rename it so it doesn't match_ - is it going to create another new collection because the name doesn't match?

**Comment by thim81** [comment]
@tillig 

While rereading your response, the behaviour used to be like described in `Repro 1` , which would allow you to target and update an existing Postman collection by using the Postman UID. It seems that during the rework of the Postman sync logic, something has been changed or the cache layer is causing a side-effect.

We would have to look into it and run some manual tests.

**Comment by thim81** [comment]
Update: it was the cache layer that caused this behaviour.

To overcome this, Portman will update the cache every time when collection UID is set.
The default behaviour where the Portman will sync based on the collection name remains the same.

If the `POSTMAN_COLLECTION_UID` is set in the .ENV or passed along to the CLI, Portman will updated the local cache based on the collections in Postman. 
- if the `POSTMAN_COLLECTION_UID` does exist in the remote Postman collection (and local cache), it will update that specific collection
- if the `POSTMAN_COLLECTION_UID` does NOT exist in the remote Postman collection (and local cache), it will create a new collection

This fix will be part of the upcoming Portman release.

**Comment by thim81** [comment]
Closing the issue, since the bug fix is solved as part of Portman v1.18.0.
