### ISSUE TITLE
Newman option "iteration-count" doesn't have any affect on Portman test

### ISSUE THREAD

**Issue by bpogrebi** [apideck-libraries/portman#395]
Having issues increasing the number of iterations during Newman execution. By default, there is only 1 iteration. Config changes using a command line and portman cli file have the same problem. Other Newman options like "insecure" do work but not "iteration-count".

**Comment by thim81** [comment]
hi @bpogrebi 

Can you share your Newman config?

On the discussion board, there is an item on Newman CLI options, which might also be helpfull:
https://github.com/apideck-libraries/portman/discussions/289

**Comment by bpogrebi** [comment]
Hi @thim81,

my newman settings: 
`{
  "iteration-count": 10,
  "suppress-exit-code": false,
  "abortOnFailure": false,
  "ignore-redirects": true,
  "insecure": true
}` 
As you can see I tried all options listed in the thread you pointed out. Same result. I get only 1 iteration even during a successful run. I assume that I don't need to have newmanIterationData to be able to run same test multiple times.

Thanks.

**Comment by thim81** [comment]
hi @bpogrebi 

Thanks for the update, I'll have to give it a spin to figure out what is going wrong.

**Comment by thim81** [comment]
hi @bpogrebi, 
We found the cause and a PR is being reviewed.

Cause: The Newman CLI expects options as param-cased, while when using Newman as a NodeJS module the options as camelCase. We have foreseen that Portman automatically transforms the casing to the correct format.

**Comment by bpogrebi** [comment]
Thanks @thim81!

**Comment by thim81** [comment]
@bpogrebi The fix will be part of the next Portman release.

**Comment by bpogrebi** [comment]
@thim81 I just tested the latest version and it's still not working. Our build process runs: npm install -g @apideck/portman on a new container every time. Can you confirm that change was merged?

**Comment by thim81** [comment]
hi @bpogrebi , The issue was closed due to another tool.
There is not a new release, I'm waiting for some input on another issue to release a new version of Portman.

**Comment by thim81** [comment]
hi @bpogrebi, We just released Portman v1.18.1, which includes the Newman fix.

**Comment by bpogrebi** [comment]
@thim81 Thanks for getting this fixed! It works for me now.
