### ISSUE TITLE
Show operationID in generated collection

### ISSUE THREAD

**Issue by armen-ch** [apideck-libraries/portman#403]
It would be useful to have operation ID shown in a generated collection. It might be request name extension in case if it's impossible to show as a separate field.

![oas](https://user-images.githubusercontent.com/70989770/190213340-0585ee02-64b6-4b1e-8bea-cb4addf6078e.png)

![generatedtest](https://user-images.githubusercontent.com/70989770/190213627-9a7a77f2-4214-48a5-892c-c81a82323186.png)

**Comment by thim81** [comment]
@armen-ch The operation ID is an optional field in the OpenAPI specification. 
Postman has its own format and structure, which does not support the definition of mapping the OAS operation ID.

For now we don't plan to overwrite the default structure and keep the 1:1 mapping of the OAS summary => Postman Name & OAS Description => Postman description.

**Comment by armen-ch** [comment]
Hi @thim81, adding "operationId" to the postman collection structure doesn't affect the postman functionality and could be helpful for debugging postman collection. Though I understand your point of view of  1:1 matching to the postman structure.
Thank you

**Comment by thim81** [comment]
We are hoping that Postman would support the option to add "tags" to a request 🤞 that would be the ideal place to store the OperationId
