### ISSUE TITLE
Ordering operations with different url path and multiple folders

### ISSUE THREAD

**Issue by laurent-lemke** [apideck-libraries/portman#423]
Hey team,
Thanks for this awesome library that does great job !
I encounter the following issue when dealing with ordering :

## Context
Suppose that i have 4 requests identified through their `operationId`. 
My use-case it to invert these requests in each folder, so this :
```
- Folder 1
   - ReqA: GET /pets/:id
   - ReqB: PUT /pets/:id
- Folder 2
   - ReqC: POST /humans/:id/search
   - ReqD: GET /humans/:id
```

Will become this: 
```
- Folder 1
   - ReqB
   - ReqA
- Folder 2
   - ReqD
   - ReqC
```

Notice that i don't care that B is performed before D or C (it could or not) ; the target scope is the folder.

## Problem

From my understanding, the `orderOperations` is performed per folder (btw, you should also write it again in the example-ordering folder).
So this should make the job:
```
"orderOfOperations": [
      "reqB",
      "reqA",
      "reqD",
      "reqC"
    ]
```

Instead, I got:
```
- Folder 1
   - ReqB
   - ReqA
- Folder 2
   - ReqC
   - ReqD
```

The library seems to have ignored the last two operations orders and consider only one folder.

I am almost sure that it's related to the URL path of the request C which differs from the request D.
When both have the same URL path, the ordering is well performed.
However, even if the URL path seems to be considered in the sorted algorithm (see: orderCollectionRequests.ts) ; it should not take precedence over the one in the configuration. 

Thanks for your feedback 🙏

**Comment by laurent-lemke** [comment]
Closing in favor of https://github.com/apideck-libraries/portman/issues/424

**Comment by thim81** [comment]
hi @laurent-lemke 

I updated the example to make it more explicit, that the sorting is per folder(great suggestion).
![image](https://user-images.githubusercontent.com/952446/200179001-55b8baf2-93ab-4f0a-acba-c74227d5be86.png)

**Comment by thim81** [comment]
I recreated your openapi example, which resulted in this (without any ordering)

```yaml
openapi: 3.0.0
info:
  title: 423-Ordering folder Test
  description: Sample desc
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
tags:
  - name: pets
    description: ''
  - name: humans
    description: ''
paths:
  /pets/:id:
    get:
      operationId: get-pet
      tags:
        - pets
      summary: get a pet.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    put:
      operationId: put-pet
      tags:
        - pets
      summary: update a pet.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /humans/:id:
    get:
      operationId: get-human
      tags:
        - humans
      summary: get a human
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    put:
      operationId: put-pet
      tags:
        - humans
      summary: update human
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /humans/:id/search:
    post:
      operationId: searchUsers
      tags:
        - humans
      summary: search for user
      responses:
        '201':
          description: A JSON array of searched user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

```

![image](https://user-images.githubusercontent.com/952446/200179087-71e7c8f8-1d65-45c3-8a84-3aa0582ddd63.png)

Next I applied the ordering, like in your example:

```json
{
  "version": 1,
  "globals": {
    "stripResponseExamples": true,
    "orderOfOperations": [
      "PUT::/pets/:id",
      "GET::/pets/:id",
      "POST::/humans/:id/search",
      "GET::/humans/:id"
    ]
  }
}
```

which gave this result:
![image](https://user-images.githubusercontent.com/952446/200179208-f5953ff6-b39b-4d7b-8cd3-fe2390575a37.png)

This seems correct? Or what was your expectation?
