### ISSUE TITLE
How to handle file uploads with Portman?

### ISSUE THREAD

**Issue by danielkocot** [apideck-libraries/portman#438]
Hi,

it's not a real issue ;). But how does Portman handle testing of file uploads. In particular with content-type binary.  I can't anything in the documentation about that.

Best,
Daniel

**Comment by thim81** [comment]
Hi @danielkocot 

Havent tried it myself, but we have a number of users who use Portman in combination with File uploads.
We will give it some time to investigate it and perhaps collect the finding in the discussion section.

**Comment by danielkocot** [comment]
HI @thim81,

sounds good so far. I will move this to the discussion section.
