### ISSUE TITLE
Postman API Get Collections Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Tanmay2711** [apideck-libraries/portman#471]
Hi Team,

I am trying to synch postman collection. with below command however I am getting this error - 

command  - npx portman -l schema.json -b http://localhost:4708 -o artifacts\tests/postman.json -c portman-config.json  --syncPostman

error - Postman API Get Collections Error: unable to get local issuer certificate

portman version  - "@apideck/portman": "^1.17.0"

![image](https://user-images.githubusercontent.com/48334190/224847091-c4be905e-c7e7-4a01-ac18-823ce4e91f46.png)

tried by disabling "SSL certification verification" in postman but no luck. 
I can access collection using curl command though - 
![image](https://user-images.githubusercontent.com/48334190/224847588-c8b20b5f-b8b3-45ac-99d3-6795994a47e1.png)

.env file -
![image](https://user-images.githubusercontent.com/48334190/224848189-90cd873e-c284-46dc-961b-fa21b9409818.png)

**Comment by thim81** [comment]
@Tanmay2711 

This sound more to be a NodeJS issue.
We are using Axios to do requests for syncing the collections using the Postman API.

Could you try any of the suggestions here: https://github.com/axios/axios/issues/535#issuecomment-262299969

**Comment by Tanmay2711** [comment]
@thim81 
Thanks for pointing out correct solution. Issue is resolved after adding NODE_TLS_REJECT_UNAUTHORIZED=0 in .env file.
