### ISSUE TITLE
Global overwriteRequestHeaders doesn't insert header parameter if overwriteRequestQueryParams specified for variation test 

### ISSUE THREAD

**Issue by armen-ch** [apideck-libraries/portman#475]
The OAS specify lookup_products operation which have 400 and 401 response codes. 
![Screenshot-oas-yaml](https://user-images.githubusercontent.com/70989770/226447079-8b12839c-8d4c-4748-a4c4-7b9ed5db1bd9.png)
The Portman config has a global overwrite which instructs to **insert header parameters to all paths having "openApiOperation": "*::/(v1|v2)/securities/*"** pattern. It also has an overwriteRequestHeaders option of "overwrite" property of variation test.
![Screenshot-overwriteRequestHeaders](https://user-images.githubusercontent.com/70989770/226452620-246eca91-1a93-4de8-96e4-01a705ee4532.png)
The variation tests also specifies overwriteRequestQueryParams for symbol query parameter in variation test:
![Screenshot-overwriteRequestQueryParams](https://user-images.githubusercontent.com/70989770/226453088-5a1b5f0e-0d45-4a6a-aa3c-e39bcca3a58b.png)
In generated Postman file the header parameter is inserted to the all the variation tests requests which match the openApiOperation option pattern. But it was not inserted into the variation test request header which tests missing parameter by using overwriteRequestQueryParams option:
![Screenshot-missing-param-in-header](https://user-images.githubusercontent.com/70989770/226455654-dbb98de3-6d6c-4e53-a6f0-f170632c768f.png)

Please note that having or not having overwriteRequestHeaders parameter doesn't have any affect and used just for to show that "overwriteRequestHeaders" option of variationTests works.

**Comment by thim81** [comment]
hi @armen-ch 

Would it be possible to share your OpenAPI and Postman config as files?
That way we can try to reproduce the behavior.

**Comment by armen-ch** [comment]
Sorry, I had a typo in my openApiOperation path pattern. Looks like this works as expected. Closing ...
