### ISSUE TITLE
Overwrite requestBody adds to request Body instead of replaces whole body

### ISSUE THREAD

**Issue by savage-alex** [apideck-libraries/portman#480]
When reviewing these tests, the names suggest that the body is replaced "'should overwrite the request body with simple key value'"
https://github.com/apideck-libraries/portman/blob/4d17c0690c0d49461d007c18834724c1e19c62cf/src/application/overwrites/overwriteRequestBody.test.ts#L26

Where as other tests state "'should extend the root request body'"

When testing I found that all of the operations extended the requestBody and none replaced it entirely.

Is there a switch to change the operation from extend to fully replace please?

**Comment by nicklloyd** [comment]
Hi @savage-alex - sorry just saw this.. Been a while, but think that key should `.` to fully replace the body? While make the test fail, but worth trying and updating snapshot if it behaves as expected ...

**Comment by thim81** [comment]
@savage-alex 
We just merged the PR from @jackdclark that fixes this issue.
This fix will be part of the next Portman release.

**Comment by savage-alex** [comment]
Thanks both!
