### ISSUE TITLE
overwriteRequestSecurity causes js error on version 1.22.0

### ISSUE THREAD

**Issue by bpogy** [apideck-libraries/portman#509]
using overwriteRequestSecurity in variation tests causes JS error:
`/portman/dist/application/overwrites/overwriteRequestSecurity.js:21
    if (authConfig.type === authDefinition.type) {
                   ^
TypeError: Cannot read properties of undefined (reading 'type')`

In my test I have a bearer token populated in "globals" but I'm trying to test 401 conditions by removing the token in variation tests.
my portman config:
`
...
"openApiOperation": "GET::/*",
                "openApiResponse": "401",
                "variations": [
                    {
                        "name": "Auth_MissingToken",
                        "overwrites": [
                            {
                                "overwriteRequestSecurity": {
                                    "bearer": {
                                        "token": ""
                                    }
                                }
                            }
                        ],
                        "tests": {
....
`

**Comment by stoicz** [comment]
We're seeing the same thing, caused by entries of `overwriteRequestSecurity`, both in the `variationTests` and the `overwrites` section.
Downgrading to 1.21.0 seemed to have fixed it tho.

**Comment by stoicz** [comment]
Might be related to this discussion as well: #507

**Comment by thim81** [comment]
hi @stoicz & @bpogy 

Do you have a Portman config & (compact) OpenAPI spec that we can use to reproduce the issue?

**Comment by bpogy** [comment]
@thim81 - i do

**Comment by thim81** [comment]
hi @bpogy & @stoicz 

We have just released version v1.23.1 of Portman, which should handle this JS error.
Could you report back if the new version solved the issue, so we can close this bug?

**Comment by bpogy** [comment]
@thim81, the problem is fixed in 1.23.1.
Thank you!

**Comment by thim81** [comment]
Thanks @bpogy for the confirmation, I'll close this item.
