### ISSUE TITLE
Add config to auto disable optional query params

### ISSUE THREAD

**Issue by matt-clarson** [apideck-libraries/portman#510]
Looks like there was at one point behaviour to automatically disable query params that are flagged as optional in the OpenAPI schema (i.e. `required: false`).
This was taken out in this PR https://github.com/apideck-libraries/portman/pull/14

Would it be possible to add a config flag to opt-in to this behaviour - I have a lot of requests with a lot of optional query params, and I'd like to be able to quickly setup a happy-path postman collection - having to manually disable all the parameters is a pain.

**Comment by matt-clarson** [comment]
Happy to contribute a PR to help this along if it's accepted as a proposal

**Comment by thim81** [comment]
hi @matt-clarson 

Can you provide me simple OpenAPI example and what you would the result to be from the example?

**Comment by thim81** [comment]
@matt-clarson It sounds like a use-full addition, but if possible could you share an example and the expected result?

**Comment by thim81** [comment]
hi @matt-clarson 

Since release [v.1.26.0](https://github.com/apideck-libraries/portman/blob/main/CHANGELOG.md#v1260---2024-01-16) this is now possible.
