### ISSUE TITLE
Publish 1.22.1

### ISSUE THREAD

**Issue by yndo97** [apideck-libraries/portman#519]
@nicklloyd could you please publish a new version to release these changes - https://github.com/apideck-libraries/portman/pull/517

**Comment by thim81** [comment]
hi @yndo97 

We want to include 2 more PRs in the next PR. We have asked for some minor changes to the contributors and if things go well, we will release a new version.

If it takes longer, we will release a new version without the PRs.

**Comment by yndo97** [comment]
Hey @thim81 do you have any ETA?

**Comment by thim81** [comment]
hi @yndo97 

I'm working through some failing unit tests, which we need to solve before we can release a new version.
I'll keep you posted of the progress.

**Comment by thim81** [comment]
Hi @yndo97 

Closing this issue, since version 1.23.0 has just been released.

**Comment by yndo97** [comment]
Thanks a lot!
