### ISSUE TITLE
Portman appears to still Pickup deprecated Api's 

### ISSUE THREAD

**Issue by Dankilroy** [apideck-libraries/portman#533]
We have found that when adding the deprecated parameter to our OpenApi Documentation (version 3.0) in swaggerhub it appears as crossed out and is clearly not in use. However when running Portman these deprecated calls are not been excluded / section off

**Comment by thim81** [comment]
hi @Dankilroy 

Can you share an example with us, so we can try to reproduce it?

Portman provides options to filter out elements based on criteria, but I gues you are referring to a difference between a regular import of OpenAPI and a Portman conversion.

**Comment by thim81** [comment]
hi @Dankilroy 

We use the [openapi-to-postman](https://github.com/postmanlabs/openapi-to-postman/blob/develop/OPTIONS.md) module, and it has a option:

So if you define you own Postman config file, you can pass it along to Portman using `--postmanConfigFile` 
If you set `includeDeprecated :false` it will remove the deprecated endpoints.

See for an example: https://github.com/apideck-libraries/portman?tab=readme-ov-file#pass-custom-paths-for-config-files

**Comment by Dankilroy** [comment]
Thanks @thim81 that worked
