### ISSUE TITLE
Query parameters should be enabled with overwrites in variation tests

### ISSUE THREAD

**Issue by miriamgreis** [apideck-libraries/portman#557]
Before version 1.26.0, optional query parameters were enabled and with a breaking change, they are now disabled. In general, I like the new behaviour and think it makes sense, but it affects many of our variation tests.

In our variation tests, we use  `overwriteRequestQueryParams` to set specific query parameters. This worked perfectly before as query parameters were enabled by default. In issue #484 a bug was fixed that query parameters were not enabled when `disable` was set to `false`. The documentation, however, even states that `false` is the default for `disable`:
`disable (Boolean true/false | Default: false) : Disables the request query param in Postman.` 
If `false` is supposed to be the default (which makes sense in my opinion), query parameters should always be enabled automatically when overwritten in variation tests, even if `disable` is not set. Right now, this is not the case. Thus, we would need to add `"disable": false` to all our failing variation tests.

**Comment by thim81** [comment]
hi @miriamgreis 

We understand that there is side-effects of the changed query parameters behavior.

There is a quick way to revert the behavior by using `--postmanConfigFile `parameter and include the original [Postman config](https://github.com/apideck-libraries/portman?tab=readme-ov-file#pass-custom-paths-for-config-files):
https://github.com/apideck-libraries/portman/blob/main/postman-config.legacy.json

Example: --postmanConfigFile https://raw.githubusercontent.com/apideck-libraries/portman/main/postman-config.legacy.json

**Comment by miriamgreis** [comment]
Hi @thim81,

thanks for the answer. Unfortunately, the `--postmanConfigFile` option is not a workaround for us. We use Portman in a pipeline that is used by many teams and by adding this option, we either need to force many teams to include this file from now on or have to do a very complicated check whether the file exists, etc. We would like to avoid disturbance for the teams as much as possible.

For me it's also not a side-effect, but a bug as the default behaviour for `false` for the `disable` property doesn't work correctly. It's counter-intuitive that the behaviour is different between the default (`false`) and if you set `disable: false`. It should work the same.

**Comment by thim81** [comment]
hi @miriamgreis 

About the pipeline, for now, they could revert to the version [v1.25.1](https://github.com/apideck-libraries/portman/releases/tag/v1.25.1), since only in version 1.26.0 the default behavior is changed.

About:
>but a bug as the default behaviour for false for the disable property doesn't work correctly. It's counter-intuitive that the behaviour is different between the default (false) and if you set disable: false. It should work the same.

Can you elaborate since I'm not fully understanding what you mean?

**Comment by miriamgreis** [comment]
Hey @thim81,
yes that's what we're doing. Just using v1.251.

Let me try to rephrase what I see as a bug: When writing a variation test, we can use `overwriteRequestQueryParams` to set specific query parameters.

If I set `"disable": false` in the Portman config, the query parameter will be enabled correctly.

If I don't set `disable` at all, I expect the same behaviour as the documentation states that `false` is the default for `disable` (which also makes sense, because why overwriting a query parameter and then disable it at the same time?). But the behaviour is not the same. The query parameters are not enabled.

**Comment by thim81** [comment]
hi @miriamgreis 

Exploring your use-case further, am I correct that if you apply an overwrite, you would expect that the modified query param is enabled by default, unless specifically set to "disable": false?

Or are you looking for a way to enable ALL query params by default, without making them required in OpenAPI?

**Comment by miriamgreis** [comment]
Hi @thim81,

the first case which you describe. I would expect that the modified query param is enabled by default as the default for `disable` is `false`.

**Comment by thim81** [comment]
Understood.

To summarise:
- so you are OK with the default behaviour of having all query params (that are not required by OpenAPI) disabled
- As soon as you start overwrite a query param, you expect the query param to become enabled UNLESS specifically set to "disable": false

**Comment by miriamgreis** [comment]
Yes, but in the second bullet point it has to say "disable": true.
Thanks for asking and sorry if that wasn't clear from the beginning.

**Comment by thim81** [comment]
hi @miriamgreis 

We just released version 1.26.3 which includes the improved behaviour with the query params overwrites, that will be auto-enabled when a overwrite value is set.

We also applied that behaviour for the request headers.

Thanks for reporting it and sharing your use-case.

If it works as expected, let us know so we can close this item.

**Comment by miriamgreis** [comment]
Thanks a lot for fixing this so quickly, it works as expected. We will happily update to the new version now! 

Thus, I consider this closed. 😀
