### ISSUE TITLE
headersPresent test should be generated only if response headers are required by the schema.

### ISSUE THREAD

**Issue by epli2** [apideck-libraries/portman#566]
Hello Team

I've noticed an issue with the current implementation of the ContractTest generator. The test for headersPresent is always generated regardless of the value of the "required" field in the schema. However, it's possible to define optional response headers within the schema.

In cases where the response headers are marked as optional, the generator should not create a test for their presence, since these headers might not be returned by the server. This can lead to unnecessary test failures and does not accurately reflect the contract's requirements.

Could we update the generator to respect the "required" field for response headers and only generate tests when it's explicitly marked as required?

Thank you

**Comment by thim81** [comment]
hi @epli2 

That sounds like a logical option, can you share a short example of an OpenAPI so that we can use that to provide the option?

**Comment by epli2** [comment]
@thim81 
Here is an example.
```yaml
openapi: 3.1.0
info:
  title: Swagger Petstore - OpenAPI 3.1
  version: 1.0.11
paths:
  /pet:
    put:
      operationId: updatePet
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          headers:
            Some-Header:
              schema:
                type: string
              required: true # <- respect this field
components:
  schemas:
    Pet:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [10]
        name:
          type: string
          examples: [doggie]
```

According to the OpenAPI Specification, the default value for 'required' in the Parameter Object is false. As such, it would be preferable for the ContractTest generator to only generate tests when 'required' is explicitly set to true.
https://spec.openapis.org/oas/v3.1.0#fixed-fields-9

**Comment by thim81** [comment]
hi @epli2 

Thanks to your input, we have created a [PR](https://github.com/apideck-libraries/portman/pull/568) to only add tests for required headers.

**Comment by epli2** [comment]
hi @thim81 
Thank you for the prompt update and for the fix.
I've found a mistake and left a comment on the PR. I would appreciate it if you could take a look.
https://github.com/apideck-libraries/portman/pull/568#discussion_r1515482887

**Comment by thim81** [comment]
hi @epli2 

Thanks to your sharp observation, I changed the implementation to check on the required response header instead of the request header.

The PR and tests are updated, so hope you can do another review.

**Comment by epli2** [comment]
hi @thim81 
I've reviewed the changes, and everything looks good. I also tested them in our project, and they work as expected.
Thank you for the quick and thorough resolution!

**Comment by thim81** [comment]
hi @epli2 

We just release version 1.26.5 with the changes to include only the required response headers in the headersPresent test.
I'll close the issue. If it doesn't work as expected, let me know.
