### ISSUE TITLE
MissingPointerError: Token "" does not exist.

### ISSUE THREAD

**Issue by vampyar** [apideck-libraries/portman#586]
`npx @apideck/portman -envFile ../.env -u http://localhost:3000/api-yaml`

.env
```
### POSTMAN APP
POSTMAN_API_KEY=PMAK-********
POSTMAN_COLLECTION_UID=30931113-*********
```

Builder:
OS: Windows
Node: v18.20.2
NPM: 10.5.0

**Comment by vampyar** [comment]
@thim81 Yep sure its log from terminal, and I don't have any errors 
![image](https://github.com/apideck-libraries/portman/assets/6781268/618c57dc-b56d-4b96-b7eb-0cd21f4f1c86)
and I try json format and yaml format it's still crushed for me, I'm attach api-json file 
[api-json.json](https://github.com/user-attachments/files/15911065/api-json.json)

**Comment by thim81** [comment]
Thanks, I'll try to reproduce the issue.

**Comment by thim81** [comment]
hi @vampyar 

There is an issue with the openapi-json not not being a valid OpenAPI file.

There are some things not compliant with the OpenAPI specification.

You can try to validate it yourself via:
- https://apitools.dev/swagger-parser/online/
- https://editor-next.swagger.io/
<img width="901" alt="image" src="https://github.com/apideck-libraries/portman/assets/952446/c5bd1e00-0343-4946-a4a3-92faf68eb7b6">

We have created a PR to improve the OpenAPI parsing error reporting, which was too unclear.

So thanks for taking your time to report this.

**Comment by thim81** [comment]
hi @vampyar 
Did you had the chance to correct the OpenAPI issues, and afterwards did the Portman conversion worked?
