### ISSUE TITLE
Replace faker with a maintained version of the package

### ISSUE THREAD

**Issue by ST-DDT** [apideck-libraries/portman#592]
I noticed, that you are using the old version of faker, that is no longer maintained.

https://github.com/apideck-libraries/portman/blob/de0279717397abce6f7c4e08b0d62a600721b4f1/package.json#L79

You might want to switch to the maintained package `@faker-js/faker`.

- https://www.npmjs.com/package/@faker-js/faker
- https://v6.fakerjs.dev/migration-guide-v5/

It has all the versions from the old package, but received numerous updates in the meantime (including built-in types).

*Disclaimer:* I'm a maintainer of `@faker-js/faker`.

**Comment by thim81** [comment]
Thanks @ST-DDT for pointing this out. 
We were not aware. I'll make some time to migrate to @faker-js/faker and review any side-effects.

**Comment by thim81** [comment]
Reference: https://github.com/postmanlabs/postman-collection/blob/e1dfe7a038d9c218e8e0be2c592896dd18b8497b/lib/superstring/dynamic-variables.js#L179

**Comment by thim81** [comment]
hi @ST-DDT 
We just merged the PR to use your @faker-js package, so it will be included in the next release of Portman.
Curious: Are you using Portman? Or you were looking at dependents of the deprecated faker package?

Thanks again for building out such a great package. Got to love the power of OSS 🙌

**Comment by ST-DDT** [comment]
> We just merged the PR to use your @faker-js package, so it will be included in the next release of Portman.
> Thanks again for building out such a great package. Got to love the power of OSS 🙌

Awesome ❤️. Thanks for your quick reaction/fix. I can only echo your sentiments.

> Curious: Are you using Portman? Or you were looking at dependents of the deprecated faker package?

We recently received multiple bug reports/messages regarding the old package as there seems to be a GitHub-Security-Advisory related to it:

- https://github.com/advisories/GHSA-5w9c-rv96-fr7g

And since the old project cannot be found anymore, these all show up at our place.
So I searched for popular projects that might be copied/learned/forked from in the npm registry.
Not sure how much it will help with that issue, but I hope this can at least raise awareness/notify others of the change.

Have a nice week :wave:

**Comment by thim81** [comment]
hi @ST-DDT 

FYI [Portman v1.28.0 ](https://github.com/apideck-libraries/portman/blob/main/CHANGELOG.md)is just released, which includes your PR to use the @faker-js package. Thanks again for your time to contribute the PR 🙌
