### ISSUE TITLE
minimumNumberFields fuzzing does not reduced value when min in spec is 0

### ISSUE THREAD

**Issue by d-simmons** [apideck-libraries/portman#599]
I am trying to fix a test that will not pass because the fuzzing was supposed to reduce the minimum which was 0. I'm not sure if it's not equipped to handle negatives or what the issue is, but the value remains at 0 with the minimumNumberFields enabled in the fuzzing section of the portman-config. All the other fields in fuzzing are working for me.

**Comment by thim81** [comment]
Hi @d-simmons 

We are reducing the number with 1
https://github.com/apideck-libraries/portman/blob/main/src/application/Fuzzer.ts#L373

Can you share your OpenApi (or the relevant part) and your Portman configuration with the fuzzing settings? So we can try to reproduce it?

**Comment by thim81** [comment]
hi @d-simmons 

I have found the cause and created a [PR](https://github.com/apideck-libraries/portman/pull/602) to improve the fuzzing to handle 0(zero) values.

**Comment by thim81** [comment]
hi @d-simmons 

FYI [Portman v1.28.0 ](https://github.com/apideck-libraries/portman/blob/main/CHANGELOG.md)is just released, which includes the fuzzing improvements that solves the reported issue.
