### ISSUE TITLE
Regex on key for overwriteRequestQueryParams

### ISSUE THREAD

**Issue by mathifonseca** [apideck-libraries/portman#612]
It would be extremely helpful to provide regular expression support when finding the `key` for the objects in the `overwriteRequestQueryParams` option. More specifically, in [this](https://github.com/apideck-libraries/portman/blob/main/src/application/overwrites/overwriteRequestQueryParams.ts#L20) line of code.

For example, in my company, we have many possible filters in our GET endpoints for listing. All of them provide query params in the form `filter[someKey]`. In the current Portman version, I need to create a huge list of keys to do exactly the same on them.

Here's how it looks now:
```
{
  "openApiOperation": "GET::/*",
  "overwriteRequestQueryParams": [
    {
      "key": "filter[createdAt]",
      "disable": true,
      "insert": false
    },
    {
      "key": "filter[holderId]",
      "disable": true,
      "insert": false
    },
    ... many more ...
    ]
}
```

Here's how it would look with regex:
```
{
  "openApiOperation": "GET::/*",
  "overwriteRequestQueryParams": [
    {
      "keyRegex": "filter[.+]",
      "disable": true,
      "insert": false
    }
  ]
}
```

**Comment by thim81** [comment]
Hi @mathifonseca 

That is a valid use-case. 
In Portman we tend to use * as a wildcard symbol, instead of using Regex. Like "key" : "filter[*]"


Would that be good alternative or would you need the power of regex because of the complex possibilities?

**Comment by nicklloyd** [comment]
Would love this tbh - I've felt this pain personally 😅

In theory we could do both right? Ie: start with the `*` wildcard to get something implemented on the existing `key`, and if we find that the regex would allow solving more of the pain, implement a new `keyRegex`, but in that scenario, the regex should be the entire pattern - not just 'inside' the square brackets I mean....

**Comment by thim81** [comment]
hi @mathifonseca 

I just added [PR](https://github.com/apideck-libraries/portman/pull/613), that allows you to target multiple query params by using a the wildcard * character.

 For example, filter[*] matches filter[0], filter[1], etc.

**Comment by thim81** [comment]
FYI [Portman v1.28.0 ](https://github.com/apideck-libraries/portman/blob/main/CHANGELOG.md)is just released, which allows you to target multiple query params by using a the wildcard * character.
