### ISSUE TITLE
Fake Values are set On Read-Only fields in the Open API spec. 

### ISSUE THREAD

**Issue by harajara** [apideck-libraries/portman#628]
I have ran the postman collection via newman collection runner created by portman with the latest version fand found out it has a broken functionality. 

The read only fields are not sent in the request earlier, but it is present with the recent release. Kindly address this issue. 

**Working Version:** 1.28.0
**Failed Version:** 1.29.0

## Request Body 

```log

  │             "tag_group_name": "in ull",
  │             "tag_name": "sin",

```

## Error Reported 

```log
 ┌ ↓ text/plain ★ text ★ plain ★ utf8 ★ 226B
  │ request body has an error: doesn't match schema: readO
  │ nly property "tag_group_name" in request | readOnly pr
  │ operty "tag_name" in request | readOnly property "tag_
  │ group_name" in request | readOnly property "tag_name" 
  │ in request
  └
```

**Comment by thim81** [comment]
hi @harajara 

Thanks for reporting this.
In version 1.29.0, we switched to `convertV2` of the openapi-to-postman module, which has an [open issue on handling read-only properties](https://github.com/postmanlabs/openapi-to-postman/issues/748).

Could you share a minimal example of an OpenAPI with your read-only properties and the expected result of the Postman request body? We can use your case to investigate the issue and think of a fix.

Depending on our finding, we could contribute the fix to the openapi-to-postman module OR extend Portman to handle the read-only properties.

As a work-a-round for your case, we would suggest to use Portman 1.28.0, while we investigate the issue.

The v1.29.0 introduces a bug fix for the fuzzing feature and an improvement of the conversion for multiple request bodies, which sound like not relevant for your current case.

**Comment by thim81** [comment]
Update: the openapi-to-postman has [fix](https://github.com/postmanlabs/openapi-to-postman/pull/807/files) in review for this issue. As soon as this lands, we will update Portman to use the new version of openapi-to-postman.

**Comment by thim81** [comment]
hi @harajara 

We have a [PR](https://github.com/apideck-libraries/portman/pull/634) ready that handles the "readonly" properties back as before. See the PR for the details and an example.

**Comment by harajara** [comment]
Thanks @thim81. I have checked the PR https://github.com/apideck-libraries/portman/pull/634 and it looks nice. 😄 💯
