### ISSUE TITLE
Upload Postman reports success while it is not successful from Portman 

### ISSUE THREAD

**Issue by pascaldufour** [apideck-libraries/portman#660]
When uploading from Azure DevOps to Postman. It reported  the upload successful while it is not uploaded.  using 
`portman --cliOptionsFile /home/vsts/work/1/s/portman-cli-config.json
`

When you do not have Editor role in the workspace in postman you get a success reported. 
See below.  (The UID is also undefined )
<img width="735" alt="PortmanSuccessBug" src="https://github.com/user-attachments/assets/384a49d1-6a0d-4968-ad58-4b69e8e86cb5">

When changing the role to editor in postman the pipeline succeeds as expected. 
See below.  (UID is filled)
<img width="742" alt="PortmanSuccess" src="https://github.com/user-attachments/assets/d48cda91-4c01-49a6-8f17-69c720b1cd07">

I was expecting: When it was not successfully uploaded an error was reported .

**Comment by thim81** [comment]
@pascaldufour Do you happen to know what the response code of the Postman Endpoint is?

**Comment by pascaldufour** [comment]
Hi Tim, 

Currently I can not see it. 
Do you know how I can see it. 
I cannot see it in the log or RAW logs within Azure Devops

Pascal

**Comment by thim81** [comment]
hi @pascaldufour 

We have a [PR](#664) ready that will handle non-200 Postman API responses better, providing clearer failure reporting.

**Comment by thim81** [comment]
Update: we just release [Portman v1.30.4](https://github.com/apideck-libraries/portman/releases/tag/v1.30.4) which includes the improved Postman API responses handling.

If the issue is solved, feel free to close this item.

**Comment by pascaldufour** [comment]
It is solved. 

It gives now a 401.

![Uploading failPortMan401.png…]()

**Comment by pascaldufour** [comment]
Even when I have no rights in Postman to create an collection you get now an 400
<img width="973" alt="failPortMan400" src="https://github.com/user-attachments/assets/bca92fc4-edb7-4a39-8c2a-48642fa622e1">

**Comment by thim81** [comment]
Thanks @pascaldufour for reporting it and providing the screenshots. 

I m happy to see this issue got resolved.
