### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by FreyAtGit** [apideck-libraries/portman#676]
Hi, 

we have an issue with the latest version 1.30.7 on our test servers (cannot be reproduced locally). 
Any idea what has been changed or what we are doing wrong since this version (as it was running before)?

![image](https://github.com/user-attachments/assets/6b2b7c9e-de86-47bd-91c6-175fd6c01888)

Thanks in advance,
Michael

**Comment by thim81** [comment]
hi @FreyAtGit 

Can you let me know which Node version you are using?

**Comment by FreyAtGit** [comment]
Hi @thim81, I think this is the issue and solution of the issue ;)
The test servers are running an older version:
![image](https://github.com/user-attachments/assets/4aecfef9-4e5c-4959-8e04-0e664ea793c0)

Thanks for the hint, I will close the issue for now as it might take some time to update it on our test servers 👍

**Comment by thim81** [comment]
Hi @FreyAtGit 

Thanks for the feedback. 
I ll look into how to do a node version check, so that it is more straightforward to indicate this requirement.
