### ISSUE TITLE
baseUrl argument is not working

### ISSUE THREAD

**Issue by scags9876** [apideck-libraries/portman#77]
portman version: 1.2.1

Hey, I'm very excited about starting to use this package, but I'm hitting a roadblock right at just testing it out.

I'm using an openapi spec that does not include a `servers` key:
https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml

When I run portman on this, specifying a baseUrl in the cli-options json file, it creates a collection with a variable baseUrl as such:

```
  "variable": [
    {
      "type": "string",
      "value": "/",
      "key": "baseUrl"
    }
  ],
```

In the output, the newman tests start up with:

```
Run Newman against:  http://0.0.0.0:8080
```

but unfortunately, the newman tests all fail with:

```
Invalid URI "http:////pastry"
```

They are taking the baseUrl variable from the collection (`/`), and never utilizing the baseUrl argument.

Is the baseUrl argument not working?  Or, is there some configuration that I am missing?    

When I add a `servers` key to the spec, the newman tests only ever hit the first server listed in the spec, they never replace that with the baseURL specified in the command line arguments.

I also tried using the envFile, trying both `PORTMAN_BASE_URL` AND `POSTMAN_BASE_URL`, to no avail.

Here is my command line:

```
portman --cliOptionsFile portman/portman-cli.json
```

Here is my portman-cli.json file:

```json
{
  "url": "https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml",
  "baseUrl": "http://0.0.0.0:8080",
  "output": "collection.postman.json",
  "envFile": "portman/.env-portman",
  "portmanConfigFile": "portman/portman-config.json",
  "includeTests": true,
  "syncPostman": false,
  "runNewman": true
}
```

The envFile and the configFile are empty.

Let me know if i can provide more info.

**Comment by nicklloyd** [comment]
Hi @scags9876 - thanks for reporting!

Took me a while, but I managed to reproduce by passing an empty object in `portman-config.json`... 

Couple things to note. An empty config will mean Portman will not inject any tests, so Newman wouldn't actually have any tests to run. 

Also to note, if you want to try out Portman with just a default set of contract tests, you can remove the `portmanConfigFile` options from your cliOptionsFile and we take over the settings from [portman-config.default.json](https://github.com/apideck-libraries/portman/blob/main/portman-config.default.json)

That said, please make sure you pull latest (1.2.2) as in debugging your issue I noticed an bad default was set in there...

**Comment by nicklloyd** [comment]
Going to close this issue, but reach out if you run into any problems.

**Comment by scags9876** [comment]
Great!  removing the portmanConfigFile and updating to 1.3.1 fixed the problem!  Thank you.
