### ISSUE TITLE
Portman fails to read OAS doc using url with trailing '/'

### ISSUE THREAD

**Issue by jbrinkman** [apideck-libraries/portman#82]
Using NestJS, my swagger document is generated automatically at `https://{{mydomain}}/{{myapi}}/docs-json/`.  Using this URL causes Portman to fail without error.  The issue is caused by this code in the get method of DownloadService.ts
```javascript
const fileName = url.split('/').pop()
```
The correct behavior should be to strip off any trailing '/' or throw and error if it detects this case.

In my case there is a workaround, since `https://{{mydomain}}/{{myapi}}/docs-json` is also a valid endpoint.

**Comment by thim81** [comment]
@jbrinkman We have created fix to overcome to properly handle the error.
It will be included in the next release.

**Comment by thim81** [comment]
@jbrinkman We just release 1.3.2 which contains the bug fix for the trailing /

**Comment by jbrinkman** [comment]
Thank you for such fast response.
