### ISSUE TITLE
Add option to put contract tests in specific folder

### ISSUE THREAD

**Issue by nicklloyd** [apideck-libraries/portman#94]
The ability to target specific folders allows us to (for example) only run Integration Tests via Newman. 

As a user I'd like to be able to do the same for running Contract Tests only depending on ci/cd workflow. 

We can maybe add a `contractTestFolder` that when present moves operations from the root of the collection to new folder.

**Comment by thim81** [comment]
Linked to #117

**Comment by thim81** [comment]
Another great feature delivered by @nicklloyd. Closing this issue since it is part of the 1.6.0 release.
